local particles =
{
    "particles/econ/items/sniper/sniper_fall20_immortal/sniper_fall20_immortal_base_attack.vpcf",
    "particles/econ/items/vengeful/vengeful_arcana/vengeful_arcana_base_attack.vpcf",
    "particles/econ/items/vengeful/vengeful_arcana/vengeful_arcana_base_attack_v2.vpcf",
    "particles/units/heroes/hero_invoker_kid/invoker_kid_base_attack_all.vpcf",
    "particles/units/heroes/hero_dazzle/dazzle_base_attack.vpcf",
    "particles/units/heroes/hero_medusa/medusa_base_attack.vpcf",
    "particles/econ/items/luna/luna_ti9_weapon/luna_ti9_base_attack.vpcf",
    "particles/units/heroes/hero_crystalmaiden/maiden_base_attack.vpcf",
    "particles/econ/items/razor/razor_ti6/razor_base_attack_ti6.vpcf",
    "particles/units/heroes/hero_enigma/enigma_base_attack.vpcf",
    "particles/units/heroes/hero_furion/furion_base_attack.vpcf",
    "particles/units/heroes/hero_puck/puck_base_attack.vpcf",
    "particles/econ/items/vengeful/vengeful_arcana/vengeful_arcana_magic_missile.vpcf",
    "particles/econ/items/vengeful/vengeful_arcana/vengeful_arcana_magic_missile_v2.vpcf",
    "particles/econ/items/vengeful/vengeful_arcana/vengeful_arcana_magic_missile_v3.vpcf",
    "particles/econ/items/shadow_fiend/sf_fire_arcana/sf_fire_arcana_base_attack.vpcf",
    "particles/econ/items/shadow_fiend/sf_desolation/sf_base_attack_desolation_fire_arcana.vpcf",
    "particles/units/heroes/hero_leshrac/leshrac_base_attack.vpcf",
    "particles/units/heroes/hero_mirana/mirana_base_attack.vpcf",
    "particles/units/heroes/hero_templar_assassin/templar_assassin_base_attack.vpcf",
    "particles/units/heroes/hero_lone_druid/lone_druid_base_attack.vpcf",
    "particles/units/heroes/hero_nevermore/nevermore_base_attack.vpcf",
    "particles/units/heroes/hero_warlock/warlock_base_attack.vpcf",
    "particles/units/heroes/hero_lina/lina_base_attack.vpcf",
    "particles/units/heroes/hero_dragon_knight/dragon_knight_dragon_tail_dragonform_proj.vpcf",
    "particles/units/heroes/hero_windrunner/windrunner_base_attack.vpcf",
    "particles/units/heroes/hero_chen/chen_base_attack.vpcf",
    "particles/units/heroes/hero_kez/kez_sai_toss.vpcf",
    "particles/units/heroes/hero_snapfire/hero_snapfire_base_attack.vpcf",
    "particles/units/heroes/hero_lion/lion_base_attack.vpcf",
    "particles/abaddon/abaddon_attack_custom.vpcf",
    "particles/econ/items/abaddon/abaddon_alliance/abaddon_aphotic_shield_alliance.vpcf",
    "particles/units/heroes/hero_abaddon/abaddon_aphotic_shield_hit.vpcf",
    "particles/econ/items/earth_spirit/earth_spirit_ti6_boulder/espirit_ti6_rollingboulder.vpcf",
    "particles/econ/world/towers/ti10_dire_tower/ti10_dire_tower_attack.vpcf",
    "particles/custom_hud/spell_level_max.vpcf",
    "particles/replace_hud/custom_tooltip_particle.vpcf",
    "particles/wood_ui_pfx/time_fx.vpcf",
    "particles/challenge_fx/challenge_fx.vpcf",
    "particles/ui/pass_flares.vpcf",
    "particles/aoe_ability_boss/aoe_ability_boss.vpcf",
    "particles/sub_card_fx/sub_card_fx.vpcf",
    "particles/pass_ui/pass_ui_smoke.vpcf",
    "particles/companiun_hud/companiun_hud_fx.vpcf",
    "particles/companiun_hud/companiun_hud_back.vpcf",
    "particles/aoe_ability_boss/explosion_aoe.vpcf",
    "particles/chest_ui/chest_ui_rays_upd.vpcf",
    "particles/aoe_ability_boss/warning_aoe.vpcf",
    "particles/chest_dropped/chest_dropped.vpcf",
    "particles/item_rare_border.vpcf",
    "particles/slyrak_background_fire_base.vpcf",
    "particles/lava_furnace/lava_furnace.vpcf",
    "particles/furnace_level_a/furnace_level_a.vpcf",
    "particles/item_fx_inventory/item_fx_inventory.vpcf",
    "particles/start_game_portal/start_game_portal.vpcf",
    "particles/units/heroes/hero_morphling/morphling_base_attack.vpcf",
    "particles/units/heroes/hero_lone_druid/lone_druid_battle_cry_overhead.vpcf",
    "particles/props/creep_banners/dire_creep_banner_ring.vpcf",
    "particles/creatures/creep_banner.vpcf",
    "particles/units/heroes/hero_venomancer/venomancer_noxious_contagion_buff.vpcf",
    "particles/econ/items/centaur/centaur_2022_immortal/centaur_2022_immortal_stampede_crimson_overhead.vpcf",
    "particles/econ/events/crownfall/high_five_crownfall_overhead.vpcf",
    "particles/econ/events/ti9/teleport_end_ti9.vpcf",
    "particles/econ/events/fall_2021/teleport_end_fall_2021_lvl3.vpcf",
    "particles/creatures/aghanim/aghanim_blink_arrival.vpcf",
    "particles/econ/world/towers/ti10_dire_tower/ti10_dire_tower_cyan_attack.vpcf",
    "particles/events/crownfall/survivors/enemies/creep_dire_hulk_swipe_left.vpcf",
    "particles/events/crownfall/survivors/enemies/creep_dire_hulk_swipe_right.vpcf",

    "particles/events/crownfall/survivors/abilities/snapfire/snapfire_frostivus_lizard_blobs_arced.vpcf",
    "particles/econ/items/snapfire/snapfire_frostivus_2023/hero_snapfire_frostivus_ultimate_calldown.vpcf",
    "particles/econ/items/snapfire/snapfire_frostivus_2023/snapfire_frostivus_ultimate_impact.vpcf",
    "particles/econ/items/snapfire/snapfire_frostivus_2023/snapfire_frostivus_ultimate_linger.vpcf",
    
    -- Artefacts
    "particles/firework_splitshot/firework_splitshot_stunned.vpcf",
    "particles/firework_splitshot/firework_splitshot_proj.vpcf",
    "particles/econ/items/crystal_maiden/ti7_immortal_shoulder/cm_ti7_immortal_frostbite.vpcf",
    "particles/econ/items/luna/luna_ti9_weapon/luna_ti9_moon_glaive_bounce.vpcf",

    -- Hero Ultimates
    "particles/units/heroes/hero_omniknight/omniknight_shard_hammer_of_purity_heal.vpcf",
    "particles/invoker/invoker_ultimate.vpcf",
    "particles/invoker/invoker_ultimateb.vpcf",
    "particles/invoker/invoker_ultimate_pull.vpcf",
    "particles/boss/boss_linear_range_finder.vpcf",
    "particles/boss/boss_ability_zap_warning.vpcf",
    "particles/boss/boss_ability_zap.vpcf",
    "particles/units/heroes/hero_nyx_assassin/nyx_assassin_mana_burn.vpcf",
    "particles/econ/items/dark_willow/dark_willow_immortal_2021/dw_2021_willow_wisp_spell_impact.vpcf",
    "particles/econ/items/dark_willow/dark_willow_immortal_2021/dw_2021_willow_wisp_spell_marker.vpcf",
    "particles/units/heroes/hero_clinkz/clinkz_searing_arrow_linear_proj.vpcf",
    "particles/econ/items/invoker/invoker_ti6/invoker_tornado_ti6.vpcf",
    "particles/econ/items/luna/luna_ti9_weapon/luna_ti9_moon_glaive_bounce.vpcf",
    "particles/crystal_maiden/cm_ult_projectile.vpcf",
    "particles/econ/events/ti7/maelstorm_ti7.vpcf",
    "particles/units/heroes/hero_kunkka/kunkka_spell_torrent_splash.vpcf",
    "particles/units/heroes/hero_enigma/enigma_blackhole.vpcf",
    "particles/units/heroes/hero_furion/furion_wrath_of_nature.vpcf",
    "particles/econ/items/puck/puck_alliance_set/puck_illusory_orb_aproset_linear_projectile.vpcf",
    "particles/econ/items/leshrac/leshrac_tormented_staff/leshrac_split_tormented.vpcf",
    "particles/units/heroes/hero_dark_willow/dark_willow_bramble_root.vpcf",
    "particles/econ/items/magnataur/shock_of_the_anvil/magnataur_shockanvil.vpcf",
    "particles/units/heroes/hero_magnataur/magnataur_shockwave_erupt.vpcf",
    "particles/wraith_king/wk_ultimate_erupt.vpcf",
    "particles/econ/items/void_spirit/void_spirit_immortal_2021/void_spirit_immortal_2021_astral_step.vpcf",
    "particles/econ/items/void_spirit/void_spirit_immortal_2021/void_spirit_immortal_2021_astral_step_impact.vpcf",
    "particles/units/heroes/hero_void_spirit/pulse/void_spirit_pulse.vpcf",
    "particles/econ/items/windrunner/windrunner_ti6/windrunner_spell_powershot_ti6.vpcf",
    "particles/econ/items/windrunner/windrunner_ti6/windrunner_spell_powershot_channel_ti6.vpcf",
    "particles/econ/items/pudge/hungry_clown/hungry_clown_rot.vpcf",
    "particles/units/heroes/hero_ursa/ursa_overpower_buff.vpcf",
    "particles/chen/chen_holy_persuasion.vpcf",
    "particles/econ/items/sand_king/sandking_barren_crown/sandking_rubyspire_burrowstrike.vpcf",
    "particles/econ/items/mirana/mirana_ti8_immortal_mount/mirana_ti8_immortal_leap_start_embers.vpcf",
    "particles/econ/items/mirana/mirana_ti8_immortal_mount/mirana_ti8_immortal_leap_trail.vpcf",
    "particles/units/heroes/hero_sandking/sandking_epicenter.vpcf",
    "particles/units/heroes/hero_sandking/sandking_epicenter_ring.vpcf",
    "particles/status_fx/status_effect_wraithking_ghosts.vpcf",
    "particles/units/heroes/hero_earth_spirit/espirit_magnetize_pulse.vpcf",
    "particles/units/heroes/hero_legion_commander/legion_commander_courage_hit.vpcf",
    "particles/units/heroes/hero_omniknight/omniknight_damage_heal_burst_flash.vpcf",
    "particles/shadow_fiend/shadow_fiend_ult_explosion.vpcf",
    "particles/econ/items/mirana/mirana_starstorm_bow/mirana_starstorm_starfall_attack.vpcf",
    "particles/econ/items/sven/sven_warcry_ti5/sven_warcry_cast_arc_lightning.vpcf",
    "particles/lockjaw/lockjaw_proc_explosion.vpcf",
    "particles/status_fx/status_effect_terrorblade_reflection.vpcf",
    "particles/lina/lina_ground_fire.vpcf",
    "particles/econ/items/lina/lina_ti7/light_strike_array_pre_ti7.vpcf",
    "particles/econ/items/lina/lina_ti7/lina_spell_light_strike_array_ti7.vpcf",
    "particles/units/heroes/hero_morphling/morphling_adaptive_strike_agi_proj.vpcf",
    "particles/econ/items/morphling/morphling_ethereal/morphling_adaptive_strike_ethereal.vpcf",
    "particles/morphling/morphling_ultimate_aoe_splash.vpcf",
    "particles/units/heroes/hero_snapfire/snapfire_lizard_blobs_arced.vpcf",
    "particles/units/heroes/hero_snapfire/hero_snapfire_ultimate_calldown.vpcf",
    "particles/units/heroes/hero_snapfire/hero_snapfire_ultimate_impact.vpcf",
    "particles/units/heroes/hero_snapfire/hero_snapfire_ultimate_linger.vpcf",
    "particles/units/heroes/hero_kez/kez_vulnerable_marker.vpcf",
    "particles/units/heroes/hero_kez/kez_sai_ultimate_crit.vpcf",
    "particles/units/heroes/hero_kez/kez_katana_echo_strike_cast.vpcf",
    "particles/units/heroes/hero_kez/kez_katana_echo_strike.vpcf",
    "particles/econ/items/lion/lion_ti9/lion_spell_impale_ti9.vpcf",
    "particles/units/heroes/hero_lion/lion_spell_finger_of_death.vpcf",
    "particles/units/heroes/hero_lion/lion_spell_voodoo.vpcf",
    "particles/econ/items/phantom_lancer/phantom_lancer_immortal_ti6/phantom_lancer_immortal_ti6_spiritlance.vpcf",
    "particles/units/heroes/hero_phantom_lancer/phantom_lancer_spawn_illusion.vpcf",
    "particles/units/heroes/hero_phantom_lancer/phantomlancer_illusion_destroy.vpcf",
    "particles/units/heroes/hero_mars/mars_shield_of_mars.vpcf",
    "particles/econ/items/mars/mars_fall20_immortal_shield/mars_fall20_immortal_shield_bash.vpcf",
    "particles/units/heroes/hero_mars/mars_shield_bash_crit.vpcf",

    -- Neutral Items
    "particles/econ/events/seasonal_reward_line_fall_2025/radiance_owner_fallrewardline_2025.vpcf",
    "particles/items_fx/desolator_projectile.vpcf",
    "particles/items3_fx/lotus_orb_reflect.vpcf",
    "particles/items5_fx/magic_lamp.vpcf",
    "particles/units/heroes/hero_ogre_magi/ogre_magi_fire_shield_bubble.vpcf",
    "particles/items4_fx/meteor_hammer_spell.vpcf",
    "particles/items5_fx/minotaur_horn.vpcf",
    "particles/units/heroes/hero_skeletonking/wraith_king_ghosts_ambient.vpcf",
    "particles/units/heroes/hero_phantom_assassin_persona/pa_persona_crit_impact.vpcf",
    "particles/events/crownfall/survivors/abilities/techies/techies_explosion_land_mine_explode.vpcf",
    "particles/units/heroes/hero_phoenix/phoenix_supernova_reborn.vpcf",

    "particles/econ/items/faceless_void/faceless_void_arcana/faceless_void_arcana_time_walk_combined.vpcf",
    "particles/econ/items/faceless_void/faceless_void_bracers_of_aeons/fv_bracers_of_aeons_backtrack.vpcf",
    "particles/units/heroes/hero_faceless_void/faceless_void_time_lock_bash.vpcf",
    "particles/units/heroes/hero_faceless_void/faceless_void_chronosphere.vpcf",
    "particles/status_fx/status_effect_faceless_chronosphere.vpcf",
    "particles/status_fx/status_effect_chemical_rage.vpcf",
    "particles/econ/items/alchemist/alchemist_aurelian_weapon/alchemist_chemical_rage_aurelian.vpcf",
    "particles/events/crownfall/survivors/abilities/kez/kez_vulnerable_marker_ray.vpcf",
    "particles/anvil_ui/anvil_ui.vpcf",
    
    -- Aghanim bosses
    "particles/shard/aghanim_bubble.vpcf",
    "particles/shard/aghanim_new_chain.vpcf",
    "particles/shard/aghanim_blood.vpcf",
    "particles/shard/aghanim_wrength_chainpair.vpcf",
    "particles/shard/aghanim_lesh_tormented.vpcf",
    "particles/shard/aghanim_hedhehohg.vpcf",
    "particles/shard/aghanim_cooldown.vpcf",
    "particles/shard/aghanim_ray_impact.vpcf",
    "particles/shard/aghanim_point_attack/aghanim_point_attack.vpcf",
    "particles/units/heroes/hero_elder_titan/elder_titan_echo_stomp_impact_magical.vpcf",
    "particles/shard/aghanim_crystal_attack.vpcf",
    "particles/shard/tinker_mech.vpcf",
    "particles/shard/status_effect_avatar_aghanim.vpcf",
    "particles/shard/dddd_chain.vpcf",
    "particles/shard/aghs_bash.vpcf",
    "particles/shard/aghs_crit.vpcf",
    "particles/shard/aghs_fire_debuff.vpcf",
    "particles/shard/aghs_mech_tr.vpcf",
    "particles/shard/aghs_cast_range_debuff.vpcf",
    "particles/shard/armor_debufff_aghanim.vpcf",
    "particles/shard/elder_aghs.vpcf",
    "particles/creatures/aghanim/staff_beam.vpcf",
    "particles/creatures/aghanim/staff_beam_water.vpcf",
    "particles/creatures/aghanim/staff_beam_linger.vpcf",
    "particles/creatures/aghanim/aghanim_beam_burn.vpcf",
    "particles/creatures/aghanim/aghanim_debug_ring.vpcf",
    "particles/creatures/aghanim/aghanim_beam_channel.vpcf",
    "particles/creatures/aghanim/aghanim_preimage.vpcf",
    "particles/creatures/aghanim/aghanim_stomp_magical.vpcf",
    "particles/creatures/aghanim/aghanim_pulse_nova.vpcf",
    "particles/econ/items/elder_titan/elder_titan_ti7/elder_titan_echo_stomp_cast_combined_detail_ti7.vpcf",
    "particles/creatures/aghanim/aghanim_crystal_attack_impact.vpcf",
    "particles/units/heroes/hero_winter_wyvern/wyvern_splinter_blast.vpcf",
    "particles/shard/crystal_debuff_impact.vpcf",
    "particles/act_2/siltbreaker_channel.vpcf",
    "particles/units/heroes/hero_tidehunter/tidehunter_gush_upgrade.vpcf",
    "particles/units/heroes/hero_tidehunter/tidehunter_gush_splash.vpcf",
    "particles/units/heroes/hero_slardar/slardar_water_puddle.vpcf",
    "particles/econ/taunts/snapfire/snapfire_taunt_bubble.vpcf",
    "particles/econ/taunts/snapfire/snapfire_taunt_bubble_pop.vpcf",
    "particles/units/heroes/hero_leshrac/leshrac_split_earth_aoe.vpcf",
    "particles/units/heroes/hero_muerta/muerta_spell_fear_debuff.vpcf",
    "particles/units/heroes/hero_muerta/muerta_spell_fear_debuff_status.vpcf",
    "particles/units/heroes/hero_tinker/tinker_defense_matrix.vpcf",
    "particles/econ/events/fall_2021/force_staff_fall_2021.vpcf",
    "particles/units/heroes/hero_mars/mars_spear_burning_trail.vpcf",
    "particles/units/heroes/hero_elder_titan/elder_titan_echo_stomp_magical.vpcf",
    "particles/units/heroes/hero_rattletrap/rattletrap_jetpack.vpcf",
    "particles/units/heroes/hero_wisp/wisp_overcharge.vpcf",
    "particles/units/heroes/hero_techies/techies_remote_mines_detonate.vpcf",
    "particles/units/heroes/hero_techies/techies_remote_cart_explode.vpcf",
    "particles/units/heroes/hero_techies/techies_land_mine_explode.vpcf",
    "particles/units/heroes/hero_techies/techies_blast_off_trail.vpcf",
    "particles/units/heroes/hero_techies/techies_suicide.vpcf",
    "particles/units/heroes/hero_techies/techies_blast_off.vpcf",
    "particles/creatures/aghanim/aghanim_crystal_attack.vpcf",

    -- Cards
    "particles/units/heroes/hero_huskar/huskar_inner_fire.vpcf",
    "particles/units/heroes/hero_lich/lich_frost_nova.vpcf",
    "particles/units/heroes/heroes_underlord/underlord_pitofmalice.vpcf",
    "particles/units/heroes/hero_omniknight/omniknight_hammer_of_purity_projectile.vpcf",
    "particles/units/heroes/hero_omniknight/omniknight_shard_hammer_of_purity_target.vpcf",
    "particles/units/heroes/hero_zuus/zuus_lightning_bolt.vpcf",
    "particles/econ/items/abaddon/abaddon_alliance/abaddon_aphotic_shield_alliance_explosion.vpcf",
    "particles/units/heroes/hero_ringmaster/ringmaster_box_dust_kickup.vpcf",
    "particles/status_fx/status_effect_ringmaster_box.vpcf",
    "particles/clown_set/ringmaster_escape_act_target.vpcf",
    "particles/units/heroes/hero_ringmaster/ringmaster_wheel_aoe.vpcf",
    "particles/units/heroes/hero_tusk/tusk_walruspunch_tgt.vpcf",
    "particles/units/heroes/hero_tusk/tusk_walruskick_tgt.vpcf",
    "particles/fans/fan_heaven_light.vpcf",
    "particles/fans/fan_linear_effects.vpcf",
    "particles/fans/fan_linear_effects_dance.vpcf",
    "particles/fans/fan_linear_effects_boomerang.vpcf",
    "particles/fans/fan_linear_effects_moon.vpcf",
    "particles/fans/fan_tracking_effects_boomerang.vpcf",
    "particles/fans/fan_tracking_effects.vpcf",
    "particles/items_fx/mana_execution.vpcf",
    "particles/units/heroes/hero_marci/marci_unleash_cast.vpcf",
    "particles/units/heroes/hero_largo/largo_amphibian_rhapsody_aoe.vpcf",
    "particles/units/heroes/hero_largo/largo_amphibian_rhapsody_buff_hands_burst.vpcf",
    "particles/units/heroes/hero_largo/largo_frogstomp_beat.vpcf",
    "particles/units/heroes/hero_largo/largo_frogstomp_burst.vpcf",
    "particles/units/heroes/hero_largo/largo_catchy_lick.vpcf",
    "particles/units/heroes/hero_largo/largo_catchy_lick_heal.vpcf",
    "particles/units/heroes/hero_largo/largo_croak_genius_debuff_burst.vpcf",
    "particles/units/heroes/hero_largo/largo_croak_genius_buff.vpcf",
    "particles/items_fx/avianas_feather.vpcf",
    "particles/econ/events/ti10/aegis_lvl_1000_ambient_ti10.vpcf",
    "particles/econ/items/hoodwink/hoodwink_2022_taunt/hoodwink_2022_taunt_music_notes.vpcf",
    "particles/econ/items/monkey_king/mk_ti9_immortal/mk_ti9_immortal_army_radius.vpcf",

    "particles/hero_card_bg/hero_card_bg.vpcf",
    "particles/card_bg/card_bg.vpcf",
    "particles/card_border/card_border.vpcf",

    "particles/custom_titles/titles_custom_2.vpcf",
    "particles/custom_titles/titles_custom_3.vpcf",
    "particles/custom_titles/titles_custom_1.vpcf",
    "particles/custom_titles/titles_custom_4.vpcf",
    "particles/custom_titles/titles_custom_5.vpcf",

    "particles/custom_wings/1.vpcf",
    "particles/custom_wings/2.vpcf",
    "particles/custom_wings/3.vpcf",

    "particles/up_custom_effects/tiny_astral_order_back_ambient.vpcf",
    "particles/up_custom_effects/dragon_amb.vpcf",
    "particles/up_custom_effects/und1.vpcf",

    "particles/custom_message/damage_default.vpcf",
    "particles/custom_message/physical_crit_damage.vpcf",
    "particles/custom_message/magical_crit.vpcf",

    "particles/custom_message/exp.vpcf",
    "particles/custom_message/gold.vpcf",
    "particles/custom_message/souls.vpcf",
    "particles/custom_message/wood.vpcf",

    "particles/ui/ui_card_to_dust_custom.vpcf",

    "particles/companions/pika_base_attack.vpcf",
    "particles/companions/pika_arc_.vpcf",
    "particles/companions/puff_song.vpcf",
    "particles/econ/items/puck/puck_alliance_set/puck_base_attack_aproset.vpcf",
    "particles/econ/items/keeper_of_the_light/kotl_weapon_arcane_staff/keeper_base_attack_arcane_staff.vpcf",
    "particles/units/heroes/hero_treant/treant_leech_seed.vpcf",
    "particles/units/heroes/hero_treant/treant_leech_seed_projectile.vpcf",
    "particles/units/heroes/hero_treant/treant_leech_seed_damage_pulse.vpcf",

    "particles/units/heroes/hero_jakiro/jakiro_base_attack_dual.vpcf",
    "particles/neutral_fx/mud_golem_hurl_boulder.vpcf",
    "particles/units/heroes/hero_jakiro/jakiro_dual_breath_firebreath.vpcf",

    -- Boss Rush bosses
    "particles/econ/items/oracle/oracle_carnival/oracle_carnival_base_attack.vpcf",
    "particles/units/heroes/hero_ringmaster/ringmaster_base_attack.vpcf",
    "particles/units/heroes/hero_tinker/tinker_base_attack.vpcf",
    "particles/units/heroes/hero_axe/axe_culling_blade.vpcf",
    "particles/units/heroes/hero_axe/axe_culling_blade_kill.vpcf",
    "particles/econ/items/bristleback/bristleback_dark_carnival/bristleback_carnival_quill_spray.vpcf",
    "particles/units/heroes/hero_bristleback/bristleback_quill_spray_impact.vpcf",
    "particles/units/heroes/hero_morphling/morphling_waveform.vpcf",
    "particles/units/heroes/hero_oracle/oracle_purifying_flames.vpcf",
    "particles/units/heroes/hero_tinker/tinker_missile.vpcf",
    "particles/units/heroes/hero_tinker/tinker_missle_explosion.vpcf",
    "particles/units/heroes/hero_tinker/tinker_missile_dud.vpcf",
    "particles/econ/items/legion/legion_dark_carnival/legion_duel_carnival_ring.vpcf",
    "particles/units/heroes/hero_legion_commander/legion_commander_duel_victory.vpcf",
    "particles/units/heroes/hero_legion_commander/legion_commander_carnival_odds.vpcf",
    "particles/units/heroes/hero_axe/axe_counterhelix.vpcf",
    "particles/econ/items/bristleback/bristleback_dark_carnival/bristleback_carnival_nasal_goo_proj.vpcf",
    "particles/econ/items/bristleback/bristleback_dark_carnival/bristleback_carnival_nasal_goo_debuff.vpcf",
    "particles/units/heroes/hero_oracle/oracle_false_promise_cast.vpcf",
    "particles/units/heroes/hero_oracle/oracle_false_promise_cast_enemy.vpcf",
    "particles/units/heroes/hero_oracle/oracle_false_promise_indicator.vpcf",
    "particles/units/heroes/hero_oracle/oracle_false_promise_dmg.vpcf",
    "particles/econ/items/tinker/tinker_ti10_immortal_laser/tinker_ti10_immortal_laser.vpcf",
    "particles/units/heroes/hero_ringmaster/ringmaster_wheel_projectile_linear.vpcf",
    "particles/units/heroes/hero_ringmaster/ringmaster_ult_custom.vpcf",
    "particles/units/heroes/hero_ringmaster/ringmaster_wheel_dagger.vpcf",
    "particles/units/heroes/hero_ringmaster/ringmaster_dagger_target_bleed_parent.vpcf",

    "particles/catapult/catapult_projectile.vpcf",
    "particles/catapult/catapult_projectile_explosion.vpcf",
    "particles/catapult/hero_snapfire_frostivus_ultimate_calldown.vpcf",
    "particles/econ/creeps/creep_2021_dire/creep_2021_dire_siege_death.vpcf",
    "particles/base_static/team_portal_ambient.vpcf",
    "particles/base_static/team_portal_ambient.vpcf",
    "particles/pokemon_spawn/pokemon_spawn_list.vpcf",
    "particles/pokemon_spawn/pokemon_spawn.vpcf",
}

local particle_folders = {
    "particles/units/heroes/hero_alchemist",
}

local sounds =
{
    "soundevents/levelup_sounds.vsndevts",
    "soundevents/custom_sounds.vsndevts",

    "soundevents/game_sounds_heroes/game_sounds_faceless_void.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_sniper.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_huskar.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_phoenix.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_medusa.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_lich.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_zuus.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_invoker.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_dazzle.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_luna.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_crystalmaiden.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_razor.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_kunkka.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_enigma.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_furion.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_puck.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_dark_willow.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_magnataur.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_legion_commander.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_nevermore.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_mirana.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_lycan.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_templar_assassin.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_omniknight.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_chaos_knight.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_skeletonking.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_earth_spirit.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_void_spirit.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_sandking.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_ringmaster.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_tusk.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_brewmaster.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_winter_wyvern.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_tidehunter.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_techies.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_tinker.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_elder_titan.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_mars.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_rattletrap.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_leshrac.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_dragon_knight.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_lina.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_windrunner.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_pudge.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_ursa.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_chen.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_morphling.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_snapfire.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_kez.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_alchemist.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_lion.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_abaddon.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_phantom_lancer.vsndevts",

    -- Boss Rush boss abilities / soundsets
    "soundevents/game_sounds_heroes/game_sounds_axe.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_bristleback.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_oracle.vsndevts",
    "soundevents/game_sounds_heroes/game_sounds_treant.vsndevts",
}

local models =
{
    "models/heroes/sniper/sniper_custom.vmdl",
    "models/heroes/invoker/invoker_custom.vmdl",
    "models/heroes/dazzle/dazzle_custom.vmdl",
    "models/heroes/medusa/medusa_custom.vmdl",
    "models/heroes/luna/luna_custom.vmdl",
    "models/heroes/crystal_maiden_custom/crystal_maiden_arcana.vmdl",
    "models/heroes/razor/razor_custom.vmdl",
    "models/heroes/kunkka/kunkka_custom.vmdl",
    "models/heroes/enigma/enigma_custom.vmdl",
    "models/heroes/furion/furion_custom.vmdl",
    "models/heroes/puck/puck_custom.vmdl",
    "models/heroes/magnataur/magnataur_custom.vmdl",
    "models/heroes/legion/legion_commander_custom.vmdl",
    "models/heroes/shadow_fiend/shadow_fiend_arcana_custom.vmdl",
    "models/heroes/leshrac/leshrac_custom.vmdl",
    "models/heroes/mirana/mirana_custom.vmdl",
    "models/heroes/layana/lanaya_custom.vmdl",
    "models/heroes/chaos_knight/chaos_knight_custom.vmdl",
    "models/heroes/earth_spirit/earth_spirit_custom.vmdl",
    "models/heroes/wraith_king/wraith_king_arcana_custom.vmdl",
    "models/items/wraith_king/arcana/wk_arcana_skeleton.vmdl",
    "models/heroes/lina/lina_custom.vmdl",
    "models/heroes/windrunner/wr_arcana_custom.vmdl",
    "models/heroes/pudge/pudge_custom.vmdl",
    "models/heroes/ursa/ursa_custom.vmdl",
    "models/heroes/chen/chen_custom.vmdl",
    "models/heroes/morphling/morphling_custom.vmdl",
    "models/heroes/kez/kez_custom.vmdl",
    "models/heroes/snapfire/snapfire_custom.vmdl",
    "models/heroes/void_spirit/void_spirit_custom.vmdl",
    "models/heroes/faceless_void/faceless_void_custom.vmdl",
    "models/heroes/alchemist/alchemist_custom.vmdl",
    "models/heroes/lion/lion_custom.vmdl",
    "models/heroes/abaddon/abaddon_custom.vmdl",
    "models/heroes/phantom_lancer/phantom_lancer_custom.vmdl",
    "models/heroes/mars/mars_custom.vmdl",
    "models/heroes/sand_king/sand_king_custom.vmdl",
    "models/heroes/axe/axe_custom.vmdl",
    "models/heroes/ringmaster/ringmaster_box.vmdl",
    "models/heroes/bard/bard_frogling.vmdl",
    "models/heroes/bard/bard_frogling_fx.vmdl",
    "models/courier/baby_rosh/babyroshan_crownfall.vmdl",
    "models/courier/baby_rosh/babyroshan_ti10.vmdl",
    "models/courier/baby_rosh/babyroshan_winter18.vmdl",
    "models/courier/baby_rosh/babyroshan_ti9.vmdl",
    "models/courier/ram/ram.vmdl",
    "models/items/courier/beaverknight_s1/beaverknight_s1.vmdl",
    "models/items/courier/nian_courier/nian_courier.vmdl",
    "models/gameplay/attrib_tome_agi.vmdl",
    "models/gameplay/attrib_tome_int.vmdl",
    "models/heroes/techies/fx_techies_remotebomb_underhollow.vmdl",
    "models/props_gameplay/roshans_banner.vmdl",
    "models/creeps/lane_creeps/creep_2021_dire/creep_2021_dire_melee_flagbearer_mega.vmdl",
    "models/creeps/lane_creeps/creep_bad_melee/creep_bad_flagbearer.vmdl",
    "models/creeps/lane_creeps/creep_bad_melee/creep_bad_melee_flagbearer_crystal.vmdl",
    "models/creeps/lane_creeps/creep_bad_melee/creep_bad_melee_flagbearer_mega_crystal.vmdl",
    "models/creeps/lane_creeps/creep_bad_melee/creep_bad_flagbearer_mega.vmdl",
    "models/creeps/lane_creeps/ti9_crocodilian_dire/ti9_crocodilian_dire_flagbearer_melee_mega.vmdl",
    "models/sahur/tung_tung_tung_sahur.vmdl",
    "models/custom_tower/custom_tower.vmdl",
    "models/courier/trapjaw/trapjaw.vmdl",
    "models/creeps/neutral_creeps/n_creep_golem_a/neutral_creep_golem_a.vmdl",

    "models/companions/bulba/bulba.vmdl",
    "models/companions/chari/chari.vmdl",
    "models/companions/meow/meow.vmdl",
    "models/companions/pika/pika.vmdl",
    "models/companions/puff/puff.vmdl",
    "models/companions/slow/slow.vmdl",

    "models/companions/chari/chari_preview.vmdl",
    "models/companions/bulba/bulba_preview.vmdl",
    "models/companions/meow/meow_preview.vmdl",
    "models/companions/pika/pika_preview.vmdl",
    "models/companions/puff/puff_preview.vmdl",
    "models/companions/slow/slow_preview.vmdl",
}

return function(context)
    for _, p in pairs(particles) do
        PrecacheResource("particle", p, context)
    end
    for _, p in pairs(particle_folders) do
        PrecacheResource("particle_folder", p, context)
    end
    for _, p in pairs(sounds) do
        PrecacheResource("soundfile", p, context)
    end
    for _, p in pairs(models) do
        PrecacheResource("model", p, context)
    end
    local npc_units = LoadKeyValues("scripts/npc/npc_units.txt")
    for unit_name, _ in pairs(npc_units) do
        PrecacheUnitByNameSync(unit_name, context, -1)
    end
    local npc_units_custom = LoadKeyValues("scripts/npc/npc_units_custom.txt")
    for unit_name, unit_data in pairs(npc_units_custom) do
        PrecacheUnitByNameSync(unit_name, context, -1)
        if unit_data and type(unit_data) == "table" and unit_data.Model then
            PrecacheResource("model", unit_data.Model, context)
        end
    end
end
