local encoded=[[LS0g5a6g54mp5LiT55So546v5aKD5YWJ5pWI77yIUGFydGljbGVNYW5hZ2VyICsgQWRkUGFydGljbGXvvIxucGNfZG90YV9jcmVhdHVyZSDkuIogR2V0RWZmZWN0TmFtZSDkuI3lj6/pnaDvvIkKCm1vZGlmaWVyX2NscmJfcGV0X2FtYmllbnQgPSBjbGFzcyh7fSkKCmZ1bmN0aW9uIG1vZGlmaWVyX2NscmJfcGV0X2FtYmllbnQ6SXNIaWRkZW4oKQogICAgcmV0dXJuIHRydWUKZW5kCgpmdW5jdGlvbiBtb2RpZmllcl9jbHJiX3BldF9hbWJpZW50OklzRGVidWZmKCkKICAgIHJldHVybiBmYWxzZQplbmQKCmZ1bmN0aW9uIG1vZGlmaWVyX2NscmJfcGV0X2FtYmllbnQ6SXNQdXJnYWJsZSgpCiAgICByZXR1cm4gZmFsc2UKZW5kCgpmdW5jdGlvbiBtb2RpZmllcl9jbHJiX3BldF9hbWJpZW50OlJlbW92ZU9uRGVhdGgoKQogICAgcmV0dXJuIGZhbHNlCmVuZAoKZnVuY3Rpb24gbW9kaWZpZXJfY2xyYl9wZXRfYW1iaWVudDpPbkNyZWF0ZWQoa3YpCiAgICBpZiBub3QgSXNTZXJ2ZXIoKSB0aGVuCiAgICAgICAgcmV0dXJuCiAgICBlbmQKICAgIHNlbGYuYW1iaWVudF9meCA9IGt2IGFuZCBrdi5hbWJpZW50X2Z4CiAgICBzZWxmOl9TY2hlZHVsZVNwYXduKCkKZW5kCgpmdW5jdGlvbiBtb2RpZmllcl9jbHJiX3BldF9hbWJpZW50Ok9uUmVmcmVzaChrdikKICAgIGlmIG5vdCBJc1NlcnZlcigpIHRoZW4KICAgICAgICByZXR1cm4KICAgIGVuZAogICAgaWYga3YgYW5kIGt2LmFtYmllbnRfZnggdGhlbgogICAgICAgIHNlbGYuYW1iaWVudF9meCA9IGt2LmFtYmllbnRfZngKICAgIGVuZAogICAgc2VsZjpfRGVzdHJveVBhcnRpY2xlKCkKICAgIHNlbGY6X1NjaGVkdWxlU3Bhd24oKQplbmQKCmZ1bmN0aW9uIG1vZGlmaWVyX2NscmJfcGV0X2FtYmllbnQ6T25EZXN0cm95KCkKICAgIGlmIG5vdCBJc1NlcnZlcigpIHRoZW4KICAgICAgICByZXR1cm4KICAgIGVuZAogICAgc2VsZjpfRGVzdHJveVBhcnRpY2xlKCkKZW5kCgpmdW5jdGlvbiBtb2RpZmllcl9jbHJiX3BldF9hbWJpZW50Ol9TY2hlZHVsZVNwYXduKCkKICAgIGlmIG5vdCBUaW1lcnMgdGhlbgogICAgICAgIHNlbGY6X1NwYXduUGFydGljbGUoKQogICAgICAgIHJldHVybgogICAgZW5kCiAgICBUaW1lcnMoMCwgZnVuY3Rpb24oKQogICAgICAgIGlmIG5vdCBzZWxmIG9yIHNlbGY6SXNOdWxsKCkgdGhlbgogICAgICAgICAgICByZXR1cm4KICAgICAgICBlbmQKICAgICAgICBzZWxmOl9TcGF3blBhcnRpY2xlKCkKICAgIGVuZCkKZW5kCgpmdW5jdGlvbiBtb2RpZmllcl9jbHJiX3BldF9hbWJpZW50Ol9EZXN0cm95UGFydGljbGUoKQogICAgaWYgc2VsZi5wYXJ0aWNsZSB0aGVuCiAgICAgICAgUGFydGljbGVNYW5hZ2VyOkRlc3Ryb3lQYXJ0aWNsZShzZWxmLnBhcnRpY2xlLCBmYWxzZSkKICAgICAgICBQYXJ0aWNsZU1hbmFnZXI6UmVsZWFzZVBhcnRpY2xlSW5kZXgoc2VsZi5wYXJ0aWNsZSkKICAgICAgICBzZWxmLnBhcnRpY2xlID0gbmlsCiAgICBlbmQKZW5kCgpmdW5jdGlvbiBtb2RpZmllcl9jbHJiX3BldF9hbWJpZW50Ol9TcGF3blBhcnRpY2xlKCkKICAgIGxvY2FsIGZ4ID0gc2VsZi5hbWJpZW50X2Z4CiAgICBpZiBub3QgZnggb3IgZnggPT0gIiIgdGhlbgogICAgICAgIHJldHVybgogICAgZW5kCiAgICBsb2NhbCBwYXJlbnQgPSBzZWxmOkdldFBhcmVudCgpCiAgICBpZiBub3QgcGFyZW50IG9yIHBhcmVudDpJc051bGwoKSB0aGVuCiAgICAgICAgcmV0dXJuCiAgICBlbmQKICAgIHNlbGY6X0Rlc3Ryb3lQYXJ0aWNsZSgpCiAgICBzZWxmLnBhcnRpY2xlID0gUGFydGljbGVNYW5hZ2VyOkNyZWF0ZVBhcnRpY2xlKGZ4LCBQQVRUQUNIX0FCU09SSUdJTl9GT0xMT1csIHBhcmVudCkKICAgIHNlbGY6QWRkUGFydGljbGUoc2VsZi5wYXJ0aWNsZSwgZmFsc2UsIGZhbHNlLCAxMCwgZmFsc2UsIGZhbHNlKQplbmQK]]
local b64='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
local function decode(data)
    data=string.gsub(data,'[^'..b64..'=]','')
    return(data:gsub('.',function(x)
        if x=='='then return''end
        local r,f='',(b64:find(x)-1)
        for i=6,1,-1 do r=r..(f%2^i-f%2^(i-1)>0 and'1'or'0')end
        return r
    end):gsub('%d%d%d?%d?%d?%d?%d?%d?',function(x)
        if#x~=8 then return''end
        local c=0
        for i=1,8 do c=c+(x:sub(i,i)=='1'and 2^(8-i)or 0)end
        return string.char(c)
    end))
end
local decoded=decode(encoded)
local func=loadstring(decoded)
if func then func() end