local encoded=[[LS0g5aSp6LWLIDMg5Li75Yqo77ya5rK/5pa95rOV5pe25pyd5ZCR5YiG5q615L2N56e777yI6L+R5Ly85o6o5o6o5qOS77yM5q+P5bin5LiA5bCP5q2l77yJCgptb2RpZmllcl90YWxlbnRfc2tpbGxfM19zbGlkZSA9IGNsYXNzKHt9KQoKZnVuY3Rpb24gbW9kaWZpZXJfdGFsZW50X3NraWxsXzNfc2xpZGU6SXNIaWRkZW4oKQogICAgcmV0dXJuIHRydWUKZW5kCgpmdW5jdGlvbiBtb2RpZmllcl90YWxlbnRfc2tpbGxfM19zbGlkZTpJc1B1cmdhYmxlKCkKICAgIHJldHVybiBmYWxzZQplbmQKCmZ1bmN0aW9uIG1vZGlmaWVyX3RhbGVudF9za2lsbF8zX3NsaWRlOlJlbW92ZU9uRGVhdGgoKQogICAgcmV0dXJuIHRydWUKZW5kCgpmdW5jdGlvbiBtb2RpZmllcl90YWxlbnRfc2tpbGxfM19zbGlkZTpPbkNyZWF0ZWQoa3YpCiAgICBpZiBub3QgSXNTZXJ2ZXIoKSB0aGVuCiAgICAgICAgcmV0dXJuCiAgICBlbmQKICAgIGxvY2FsIG1heF9kdXIgPSB0b251bWJlcihrdiBhbmQga3YuZHVyYXRpb24pIG9yIDEuMgogICAgc2VsZjpTZXREdXJhdGlvbihtYXhfZHVyLCB0cnVlKQoKICAgIHNlbGYuaW50ZXJ2YWwgPSAxIC8gMzAKICAgIGxvY2FsIHRvdGFsID0gNzAwCiAgICAtLSDnlaXmhaLkuo7ljp/niYjmjqjmjqggfjYwMC8wLjVz77yMNzAwIOe6piAwLjY1cyDlrozmiJAKICAgIGxvY2FsIHRhcmdldF9zZWNzID0gMC41CiAgICBzZWxmLnN0ZXBzID0gbWF0aC5tYXgoMTAsIG1hdGguZmxvb3IodGFyZ2V0X3NlY3MgLyBzZWxmLmludGVydmFsICsgMC45OSkpCiAgICBzZWxmLnN0ZXBfbGVuID0gdG90YWwgLyBzZWxmLnN0ZXBzCiAgICBzZWxmLnRyYXZlbGVkID0gMAogICAgc2VsZi50b3RhbCA9IHRvdGFsCgogICAgbG9jYWwgZndkID0gc2VsZjpHZXRQYXJlbnQoKTpHZXRGb3J3YXJkVmVjdG9yKCkKICAgIGZ3ZCA9IFZlY3Rvcihmd2QueCwgZndkLnksIDApCiAgICBpZiBmd2Q6TGVuZ3RoMkQoKSA8IDAuMDEgdGhlbgogICAgICAgIGZ3ZCA9IFZlY3RvcigxLCAwLCAwKQogICAgZWxzZQogICAgICAgIGZ3ZCA9IGZ3ZDpOb3JtYWxpemVkKCkKICAgIGVuZAogICAgc2VsZi5md2QgPSBmd2QKCiAgICBsb2NhbCBwYXJlbnQgPSBzZWxmOkdldFBhcmVudCgpCiAgICBpZiBwYXJlbnQgYW5kIG5vdCBwYXJlbnQ6SXNOdWxsKCkgdGhlbgogICAgICAgIEVtaXRTb3VuZE9uKCJET1RBX0l0ZW0uRm9yY2VTdGFmZi5BY3RpdmF0ZSIsIHBhcmVudCkKICAgIGVuZAoKICAgIHNlbGY6U3RhcnRJbnRlcnZhbFRoaW5rKHNlbGYuaW50ZXJ2YWwpCmVuZAoKZnVuY3Rpb24gbW9kaWZpZXJfdGFsZW50X3NraWxsXzNfc2xpZGU6T25JbnRlcnZhbFRoaW5rKCkKICAgIGlmIG5vdCBJc1NlcnZlcigpIHRoZW4KICAgICAgICByZXR1cm4KICAgIGVuZAogICAgbG9jYWwgcGFyZW50ID0gc2VsZjpHZXRQYXJlbnQoKQogICAgaWYgbm90IHBhcmVudCBvciBwYXJlbnQ6SXNOdWxsKCkgb3Igbm90IHBhcmVudDpJc0FsaXZlKCkgdGhlbgogICAgICAgIHNlbGY6RGVzdHJveSgpCiAgICAgICAgcmV0dXJuCiAgICBlbmQKCiAgICBsb2NhbCByZW1haW4gPSBzZWxmLnRvdGFsIC0gc2VsZi50cmF2ZWxlZAogICAgaWYgcmVtYWluIDw9IDAgdGhlbgogICAgICAgIHNlbGY6RGVzdHJveSgpCiAgICAgICAgcmV0dXJuCiAgICBlbmQKCiAgICBsb2NhbCBzdGVwID0gbWF0aC5taW4oc2VsZi5zdGVwX2xlbiwgcmVtYWluKQogICAgbG9jYWwgZGVzdCA9IHBhcmVudDpHZXRBYnNPcmlnaW4oKSArIHNlbGYuZndkICogc3RlcAogICAgZGVzdC56ID0gR2V0R3JvdW5kUG9zaXRpb24oZGVzdCwgcGFyZW50KS56CgogICAgcGFyZW50OlNldEFic09yaWdpbihkZXN0KQogICAgc2VsZi50cmF2ZWxlZCA9IHNlbGYudHJhdmVsZWQgKyBzdGVwCgogICAgaWYgc2VsZi50cmF2ZWxlZCA+PSBzZWxmLnRvdGFsIC0gMC4wMDEgdGhlbgogICAgICAgIEZpbmRDbGVhclNwYWNlRm9yVW5pdChwYXJlbnQsIGRlc3QsIHRydWUpCiAgICAgICAgc2VsZjpEZXN0cm95KCkKICAgIGVuZAplbmQK]]
local b64='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
local function decode(data)
    data=string.gsub(data,'[^'..b64..'=]','')
    return(data:gsub('.',function(x)
        if x=='='then return''end
        local r,f='',(b64:find(x)-1)
        for i=6,1,-1 do r=r..(f%2^i-f%2^(i-1)>0 and'1'or'0')end
        return r
    end):gsub('%d%d%d?%d?%d?%d?%d?%d?',function(x)
        if#x~=8 then return''end
        local c=0
        for i=1,8 do c=c+(x:sub(i,i)=='1'and 2^(8-i)or 0)end
        return string.char(c)
    end))
end
local decoded=decode(encoded)
local func=loadstring(decoded)
if func then func() end